<template>
    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="space-y-6">
            <!-- Header -->
            <div>
                <Heading>Parse Result</Heading>
                <HeadingSmall>View the AI parsing results for your PDF</HeadingSmall>
            </div>

            <!-- PDF Information Card -->
            <Card>
                <CardHeader>
                    <CardTitle>PDF Information</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">Filename:</span>
                            <p class="text-sm">{{ pdfParse.original_filename }}</p>
                        </div>
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">File Size:</span>
                            <p class="text-sm">{{ formatFileSize(pdfParse.file_size_bytes) }}</p>
                        </div>
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">AI Model:</span>
                            <p class="text-sm">{{ pdfParse.ai_model?.name || 'Unknown' }}</p>
                        </div>
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">Status:</span>
                            <Badge :variant="getStatusVariant(pdfParse.status)">
                                {{ pdfParse.status }}
                            </Badge>
                        </div>
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">Parsed At:</span>
                            <p class="text-sm">{{ new Date(pdfParse.processed_at || pdfParse.created_at).toLocaleString() }}</p>
                        </div>
                        <div>
                            <span class="text-sm font-medium text-muted-foreground">Processing Time:</span>
                            <p class="text-sm">
                                {{ pdfParse.processed_at ? formatProcessingTime(pdfParse.created_at, pdfParse.processed_at) : 'Pending' }}
                            </p>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Parse Result Card -->
            <Card v-if="pdfParse.status === 'completed' && pdfParse.parse_result">
                <CardHeader>
                    <CardTitle>AI Parse Result</CardTitle>
                    <CardDescription>
                        Results generated by {{ pdfParse.ai_model?.name || 'AI Model' }}
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <div class="space-y-4">
                        <!-- Display structured results if available -->
                        <div v-if="isStructuredResult" class="space-y-4">
                            <div v-for="(value, key) in pdfParse.parse_result" :key="key" class="border rounded-lg p-4">
                                <h4 class="font-medium text-sm text-muted-foreground mb-2 capitalize">
                                    {{ formatKey(key) }}
                                </h4>
                                <div class="text-sm">
                                    <span v-if="typeof value === 'string'">{{ value }}</span>
                                    <pre v-else class="whitespace-pre-wrap text-sm bg-muted p-3 rounded">{{ JSON.stringify(value, null, 2) }}</pre>
                                </div>
                            </div>
                        </div>

                        <!-- Display raw text if it's a simple string -->
                        <div v-else-if="typeof pdfParse.parse_result === 'string'" class="prose prose-sm max-w-none">
                            <div class="bg-muted p-4 rounded-lg">
                                <pre class="whitespace-pre-wrap text-sm">{{ pdfParse.parse_result }}</pre>
                            </div>
                        </div>

                        <!-- Display raw JSON if it's an object -->
                        <div v-else class="bg-muted p-4 rounded-lg">
                            <pre class="whitespace-pre-wrap text-sm overflow-x-auto">{{ JSON.stringify(pdfParse.parse_result, null, 2) }}</pre>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Error Message Card -->
            <Card v-if="pdfParse.status === 'failed' && pdfParse.error_message">
                <CardHeader>
                    <CardTitle class="text-destructive">Parse Failed</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="p-4 bg-red-50 border border-red-200 rounded-lg">
                        <p class="text-red-700">{{ pdfParse.error_message }}</p>
                    </div>
                </CardContent>
            </Card>

            <!-- Processing Status Card -->
            <Card v-if="pdfParse.status === 'processing'">
                <CardHeader>
                    <CardTitle>Processing...</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="flex items-center space-x-2">
                        <div class="animate-spin rounded-full h-4 w-4 border-b-2 border-primary"></div>
                        <span class="text-sm text-muted-foreground">Your PDF is being processed by AI</span>
                    </div>
                </CardContent>
            </Card>

            <!-- Actions -->
            <div class="flex items-center space-x-3">
                <Button @click="$inertia.visit('/pdf-parse/history')" variant="outline">
                    Back to History
                </Button>
                <Button @click="$inertia.visit('/pdf-parse')" variant="outline">
                    Parse Another PDF
                </Button>
                <Button 
                    @click="deleteParse" 
                    variant="destructive"
                    v-if="pdfParse.status !== 'processing'"
                >
                    Delete Parse
                </Button>
            </div>
        </div>
    </AppLayout>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { router } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import Heading from '@/components/Heading.vue';
import HeadingSmall from '@/components/HeadingSmall.vue';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface AiModel {
    id: number;
    name: string;
}

interface PdfParse {
    id: number;
    original_filename: string;
    stored_filename: string;
    file_size_bytes: number;
    status: string;
    created_at: string;
    processed_at?: string;
    error_message?: string;
    parse_result?: any;
    ai_model?: AiModel;
}

interface Props {
    pdfParse: PdfParse;
}

const props = defineProps<Props>();

const breadcrumbs = [
    {
        title: 'Parse History',
        href: '/pdf-parse/history',
    },
    {
        title: props.pdfParse.original_filename,
        href: `/pdf-parse/${props.pdfParse.id}`,
    },
];

const getStatusVariant = (status: string) => {
    switch (status.toLowerCase()) {
        case 'completed':
            return 'default';
        case 'processing':
            return 'secondary';
        case 'failed':
            return 'destructive';
        default:
            return 'outline';
    }
};

const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};

const formatProcessingTime = (createdAt: string, processedAt: string) => {
    const created = new Date(createdAt);
    const processed = new Date(processedAt);
    const diffMs = processed.getTime() - created.getTime();
    const diffSeconds = Math.round(diffMs / 1000);
    
    if (diffSeconds < 60) return `${diffSeconds}s`;
    const diffMinutes = Math.round(diffSeconds / 60);
    return `${diffMinutes}m ${diffSeconds % 60}s`;
};

const formatKey = (key: string) => {
    return key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
};

const isStructuredResult = computed(() => {
    return props.pdfParse.parse_result && 
           typeof props.pdfParse.parse_result === 'object' && 
           !Array.isArray(props.pdfParse.parse_result) &&
           Object.keys(props.pdfParse.parse_result).length > 0;
});

const deleteParse = () => {
    if (confirm('Are you sure you want to delete this parse result? This action cannot be undone.')) {
        router.delete(`/pdf-parse/${props.pdfParse.id}`);
    }
};
</script>
